require_relative "mikon/version"
require_relative "mikon/plot"
require_relative "mikon/core/array"
require_relative "mikon/core/index"
require_relative "mikon/core/series"
require_relative "mikon/core/dataframe"
